name: OntoPuS
services:
  ontopus:
    build:
        context: .
        dockerfile: ./Dockerfile
        target: ontopus
    container_name: ontopus
    hostname: ontopus
    environment:
        ONTOPUS_DATABASE_URL: "http://graphdb:7200/repositories/ontopus"
    ports:
        - "8080:8080"
  graphdb:
    image: ontotext/graphdb:11.3.0
    container_name: graphdb
    hostname: graphdb
    ports:
      - "7200:7200"
    volumes:
        -   graphdb-data:/opt/graphdb/home

volumes:
    graphdb-data:
