name: "OntoPuS"
services:
  ontopus:
    build:
      context: "."
      dockerfile: "./Dockerfile"
      target: "ontopus"
    container_name: "ontopus"
    hostname: "ontopus"
    depends_on:
      graphdb:
        condition: "service_started"
    environment:
      ONTOPUS_DATABASE_URL: "http://graphdb:7200/repositories/ontopus"
    ports:
      - "8080:8080"
    read_only: true
    tmpfs:
      - "/tmp:size=1g,mode=1777,noexec,nosuid,nodev"
  graphdb:
    image: "ontotext/graphdb:10.8.9"
    container_name: "graphdb"
    hostname: "graphdb"
    ports:
      - "7200:7200"
    volumes:
      - "graphdb-data:/opt/graphdb/home"
volumes:
  graphdb-data: null
