name: "OntoPuS"
services:
  ontopus:
    build:
      context: "."
      dockerfile: "./Dockerfile"
      target: "ontopus-full"
      args:
        - "ONTOPUS_SYSTEM_URI=${ONTOPUS_SYSTEM_URI}"
    container_name: "ontopus"
    hostname: "ontopus"
    domainname: "ontopus"
    depends_on:
      graphdb:
        condition: "service_healthy"
    environment:
      ONTOPUS_DATABASE_URL: "http://graphdb:7200/repositories/ontopus"
      ONTOPUS_SYSTEM_URI: "${ONTOPUS_SYSTEM_URI}"
      # Enable processing of forwarded headers (e.g. X-Forwarded-For) by TomCat
      SERVER_FORWARD_HEADERS_STRATEGY: "NATIVE"
      ONTOPUS_PLUGIN_WIDOCO_EXECUTION_TIMEOUT: "5m"
#    ports:
#      - "8080:8080"
    read_only: true
    volumes:
      - "ontopus-data:/data:rw"
    tmpfs:
      - "/tmp:size=1g,mode=1777,noexec,nosuid,nodev"
  graphdb:
    image: "ontotext/graphdb:10.8.9"
    container_name: "ontopus_graphdb"
    hostname: "graphdb"
    domainname: "graphdb"
#    ports:
#      - "7200:7200"
    volumes:
      - "graphdb-data:/opt/graphdb/home"
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://localhost:7200/rest/monitor/structures"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 5s
  nginx:
    image: nginx:stable-alpine-slim
    container_name: "ontopus_nginx"
    hostname: "nginx"
    domainname: "nginx"
    read_only: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # configuration
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/includes:/etc/nginx/includes
    tmpfs:
      - /var/cache/nginx
      - /var/run

volumes:
  graphdb-data: null
  ontopus-data: null
