
server {
    listen 80 default_server;
    location / {
        include /etc/nginx/includes/ontopus_proxy_pass.conf;
    }
}

# server {
#     listen 443 ssl ;
#     server_name example.com
#     ssl_certificate /etc/nginx/includes/example.com.crt
#     ssl_certificate_key /etc/nginx/includes/example.com.key
#     location / {
#         include /etc/nginx/includes/ontopus_proxy_pass.conf;
#     }
# }
