

proxy_set_header Host $host:$server_port;
proxy_set_header X-Forwarded-Host $server_name;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

proxy_pass http://ontopus:8080;


# modify html links and replace http with https
sub_filter 'href="http://' 'href="https://';
# apply to all occurrences
sub_filter_once off;
# apply only to HTML
sub_filter_types text/html;
