spring:
  profiles:
    active: "@spring.profiles.active@"
  application:
    name: OntoPuS
    version: "@project.version@"
  threads:
    virtual:
      enabled: true # enables virtual threads
  servlet:
    multipart:
      max-file-size: 10MB

# use Spring "swagger" profile to enable Swagger
springdoc:
  api-docs:
    enabled: false

logging:
  level:
    web: debug
    org:
      springframework:
        boot:
          autoconfigure:
            logging: INFO # disables conditions evaluation report
server:
  servlet:
    session:
      timeout: 10m
  tomcat:
    max-part-count: 30
