spring:
  profiles:
    active: "@spring.profiles.active@"
  application:
    name: OntoPuS
    version: "@ontopus.core.version@"
  threads:
    virtual:
      enabled: true # enables virtual threads
# use Spring "swagger" profile to enable Swagger
springdoc:
  api-docs:
    enabled: false
#  show-login-endpoint: true

server.servlet.session.timeout: 10m

ontopus:
  database:
    url: http://localhost:7200/repositories/ontopus
    driver: cz.cvut.kbss.ontodriver.rdf4j.Rdf4jDataSource
    language: en
logging:
  level:
    web: debug
